name: branch-auto-merge
on: 
  #push:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  create-branch-list:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: create branch list
        id: branches
        run: |
          git worktree add Alpha_work develop/Alpha
          git worktree add Bravo_work develop/Bravo
          git worktree list
