on: 
  #push:
  pull_request:
    types: opened
    branches: production
  workflow_dispatch:  

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: create branch list
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.pulls.get({
                               owner: context.repo.owner,
                               repo: context.repo.repo,
                               pull_number: ${{ github.event.number }}
                           });
            console.log(result.data.title)
            console.log(result.data.body)
            const result2 = await github.rest.repos.createRelease({
                               owner: context.repo.owner,
                               repo: context.repo.repo,
                               tag_name: "tagging-" + result.data.title,
                               body: result.data.body,
                               generate_release_notes: true
                             });
             //let open_list = pull_request_list.data.filter((item) => (item.closed_at == null));
             
             console.log(result2);
             //return !Object.keys(open_list).length;
