on: 
  #push:
  pull_request:
    types: opened
    branches: production
  workflow_dispatch:  

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: create branch list
        uses: actions/github-script@v6
        with:
          script: |
            echo ${{github.event.number}} 
            //const result = await github.rest.repos.createRelease({
            //                   owner: context.repo.owner,
            //                   repo: context.repo.repo,
            //                   tag_name: '20230706-2'
            //                 });
             //let open_list = pull_request_list.data.filter((item) => (item.closed_at == null));
             
             console.log(result);
             //return !Object.keys(open_list).length;
