# リリース日単位でリリースノートを作成（productionへのプルリクを対象とする）
name: Auto generate release note by release date 
on: 
  #push:
  #pull_request:
  #  types: closed
    #branches: production
  workflow_dispatch:
    inputs:
      releaseDate:
        description: 'リリース日'
        required: true
        type: string

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: create branch list
        uses: actions/github-script@v6
        with:
          script: | 
            // プルリク取得
            const pullRequests = await github.rest.pulls.list({
                                   //base: 'develop/Test',
                                   //head: 'main',
                                   owner: context.repo.owner,
                                   repo: context.repo.repo,
                                   state: 'close',
                               });
            // プルリク本文未記入＋リリース日マッチしないプルリクは除外
            // filterした後にソートした方が良いか？
            const targetPullRequests = pullRequests.data.filter(pullRequest => pullRequest.body && pullRequest.body.match(/${{ inputs.releaseDate }}/));

            // プルリク取得できない場合は処理終了
            if (!targetPullRequests) {
                console.log("リリースノート記入対象なし");
                return;
            }
            
            console.log("リリースノート記入対象プルリク数：" + targetPullRequests.length);
            
            // タグ名
            const tagNameFormat = (releaseDate) => "tagging-" + releaseDate;
            // リリース名
            const releaseNameFormat = (releaseDate) => "release-" + releaseDate;
            // リリースノートbody
            const releaseNoteFormat = (pullRequestNumber, pullRequestTitle) => "#" + pullRequestNumber + " " + pullRequestTitle;
            
            targetPullRequests.forEach(target => console.log(releaseNoteFormat(target.number, target.title)));
            // head: fromブランチ、 base: toブランチ
