on: 
  #push:
  pull_request:
    types: closed
    #branches: production
  workflow_dispatch:  

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: create branch list
        uses: actions/github-script@v6
        with:
          script: |
            const pull = await github.rest.pulls.get({
                                   owner: context.repo.owner,
                                   repo: context.repo.repo,
                                   pull_number: ${{ github.event.number }}
                               });
            // タイトルからリリース日を取得
            const matchResult = pull.data.title.match(/.*([0-9]{4}[01][0-9][0-3][0-9]).*/);
            const yyyyMmDd = (matchResult) => {
                if (!matchResult) {
                    const current = new Date();
                    return String(current.getFullYear()) + String(current.getMonth() + 1) + String(current.getDate());
                }
                return matchResult[1];
            };
            // 取得できなかった場合は現在日付を設定
            console.log(yyyyMmDd)
            
            const result = await github.rest.repos.createRelease({
                                     owner: context.repo.owner,
                                     repo: context.repo.repo,
                                     tag_name: "tagging-" + yyyyMmDd,
                                     target_commitish: pull.data.base.ref,
                                     name: "release-" + yyyyMmDd,
                                     body: pull.data.body + " #29",
                                     generate_release_notes: true
                                 });

             console.log(result);

