on: 
  #push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:  

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: create branch list
        uses: actions/github-script@v6
        with:
          script: |
            const pull = await github.rest.pulls.get({
                               owner: context.repo.owner,
                               repo: context.repo.repo,
                               pull_number: ${{ github.event.number }}
                           });
            const yyyyMmDd = pull.data.title.match(/.+([0-9]{4}[01][0-9][0-3][0-9]).+/);
            const result = await github.rest.repos.createRelease({
                               owner: context.repo.owner,
                               repo: context.repo.repo,match()
                               tag_name: "tagging-" + yyyyMmDd,
                               name: "release-" + yyyyMmDd,
                               body: pull.data.body,
                               generate_release_notes: true
                             });
             //let open_list = pull_request_list.data.filter((item) => (item.closed_at == null));
             
             console.log(result);
             //return !Object.keys(open_list).length;
