name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: get branches
        id: branches
        run: |
          branches=$(echo '["develop/Alpha", "develop/Bravo"]' | jq -c)
          echo "value=${branches}" >> $GITHUB_OUTPUT
      - name: CheckOutMainRepository
        uses: actions/checkout@v3
   
  auto-merge:
    needs: get-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) }}
    steps:
      - run: |
          echo ${{ matrix.branch }}
          #github clientを使わない場合、リポジトリクローン＋マージが必要？
          gh issue list
        
     
  #auto-merge:
  ##  name: AutoMerge
   # runs-on: ubuntu-latest
   # steps:
   #   - name: CheckOutMergeRepository
   #     uses: actions/checkout@v3
   #     with:
   #       ref: ${{github.ref_name}}
   #   - run: pwd
      #- name: CheckOutHeadRepository
      #  uses: actions/checkout@v3
      #  with:
      #    ref: main
    #  - name: Merge
     #   run: git merge main
        
