name: test
on:
  workflow_dispatch
jobs:
  ReviewDog:
    name: ReviewDog
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: log
        run: git log -1
