name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      # とりあえずリポジトリが無ければ、クローンする。あればプルする。
      # Github clientが入っていないのでこの対応。入っていたら不要になると思う。ghコマンドで取ってこれるので。
      - name: Clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_TOKEN}
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/0511junpei/Test
      - name: get branches
        if: ${{ success() }}
        id: branches
        run: |
          git branch
          branches=$(echo git branch)
          echo "value=${branches}" >> $GITHUB_OUTPUT
   
  auto-merge:
    needs: get-branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{ needs.get-branches.outputs.branches }}
    steps:
      - run: echo ${{ matrix.test }}
      
        
     
  #auto-merge:
  ##  name: AutoMerge
   # runs-on: ubuntu-latest
   # steps:
   #   - name: CheckOutMergeRepository
   #     uses: actions/checkout@v3
   #     with:
   #       ref: ${{github.ref_name}}
   #   - run: pwd
      #- name: CheckOutHeadRepository
      #  uses: actions/checkout@v3
      #  with:
      #    ref: main
    #  - name: Merge
     #   run: git merge main
        
