# reference: https://tech.mirrativ.stream/entry/2023/01/27/105211

name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  create-branch-list:
    runs-on: ubuntu-latest
    outputs: 
      branch_list: ${{ steps.branches.outputs.branch_list }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: create branch list
        id: branch_list
        run: |
          git fetch
          target_branches=$(git branch -a | grep remotes/origin/develop/ | sed s@remotes/origin/@\"@ | sed s/$/\",/ | sort )
          branches=$(echo $target_branches | sed s/,$// )
          echo ${branches}
          echo "branch_list=[ $branches ]" >> $GITHUB_OUTPUT
  auto-merge-branch-unit:
    needs: create-branch-list
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.create-branch-list.outputs.branch_list) }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: create pull request
        id: create-pull-request
        #run: gh pr create -B ${{ matrix.branch }} -t "Auto Merge 'main' To "${{ matrix.branch }} -b ""
        #run: git merge --no-ff
        run: |
          git fetch
          git checkout local/${{ matrix.branch }} remotes/origin/${{ matrix.branch }}
          git merge main
          git add -A
          git commit -m "Auto Merge 'main' To "${{ matrix.branch }}
          git push remotes/origin/${{ matrix.branch }}
