name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  create-branch-list:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: create branch list
        id: branches
        run: |
          branches=$(echo '["develop/Alpha", "develop/Bravo"]' | jq -c)
          echo "value=${branches}" >> $GITHUB_OUTPUT
  auto-merge-branch-unit:
    needs: create-branch-list
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.create-branch-list.outputs.branches) }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create pull request
        id: create-pull-request
        #run: gh pr create -B ${{ matrix.branch }} -t "Auto Merge 'main' To "${{ matrix.branch }} -b ""
        #run: git merge --no-ff
        run: git branch
