name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: get branches
        id: branches
        run: |
          #branches=$(echo '["develop/Alpha", "develop/Bravo"]' | jq -c)
          branches=$(echo '["test", "test2"]' | jq -c)
          echo "value=${branches}" >> $GITHUB_OUTPUT
      - name: CheckOutMainRepository
        uses: actions/checkout@v3
   
  auto-merge-branch-unit:
    needs: get-branches
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) }}
    steps:
      - name: CheckOutMergeRepository
        uses: actions/checkout@v3
      - run: |
          URI = $(gh pr create -B ${{ matrix.branch }} -t 自動マージ${{ matrix.branch }})
          echo URI
        
     
  #auto-merge:
  ##  name: AutoMerge
   # runs-on: ubuntu-latest
   # steps:
   #   - name: CheckOutMergeRepository
   #     uses: actions/checkout@v3
   #     with:
   #       ref: ${{github.ref_name}}
   #   - run: pwd
      #- name: CheckOutHeadRepository
      #  uses: actions/checkout@v3
      #  with:
      #    ref: main
    #  - name: Merge
     #   run: git merge main
        
