name: branch-auto-merge
on: 
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  auto-merge:
    name: AutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: CheckOutToRepository
      #  uses: actions/checkout@v3
      #  with:
      #    ref: ${{toJSON(github.ref_name)}}
        run: echo '${{toJSON(github)}}'
      - name: CheckOutMainRepository
        uses: actions/checkout@v3
        with:
          refs: main
