name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  auto-merge:
    name: AutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: CheckOutMergeRepository
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}
      - run: pwd
      #- name: CheckOutHeadRepository
      #  uses: actions/checkout@v3
      #  with:
      #    ref: main
      - name: Merge
        run: git merge main
        
