name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  create-branch-list:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          refs: develop/*
      - run: |
          git for-each-ref
      - name: create branch list
        id: branches
        run: |
          #branches=$(echo '["develop/Alpha", "develop/Bravo"]' | jq -c)
          branches=$(echo '["test", "test2"]' | jq -c)
          
          test=$(git for-each-ref refs/remotes/origin/test* --format="%(refname:lstrip=-1)")
          branches_test=`echo ${test[@]}`
          echo "value=${branches}" >> $GITHUB_OUTPUT
          echo ${branches_test}
  auto-merge-branch-unit:
    needs: create-branch-list
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.create-branch-list.outputs.branches) }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: create pull request
        id: create-pull-request
        continue-on-error: true
        run: gh pr create -B ${{ matrix.branch }} -t "Auto Merge 'main' To "${{ matrix.branch }} -b ""
      - name: error handling
        if: ${{ steps.create-pull-request.outcome == 'failure' }}
        run: |
          echo ${{ steps.create-pull-request.outcome }}
          echo ${{ steps.create-pull-request }}
          exit 1
      
#- name: Merge
      #  run: 
      #    gh pr merge ${{steps.create-pull-request.outputs.PULL_REQUEST_URI}} --merge

       
