name: branch-auto-merge
on: 
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  auto-merge:
    name: AutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: CheckOutToRepository
        uses: actions/checkout@v3
        with:
          ref: echo ${{github.ref}}#refs/tags/
      - name: CheckOutMainRepository
        uses: actions/checkout@v3
        with:
          refs: main
