name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: production
  workflow_dispatch:

jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: get branches
        id: branches
        run: |
          #branches=$(echo '["develop/Alpha", "develop/Bravo"]' | jq -c)
          branches=$(echo '["test", "test2"]' | jq -c)
          echo "value=${branches}" >> $GITHUB_OUTPUT
   
  auto-merge-branch-unit:
    needs: get-branches
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) }}
    steps:
      - name: CheckOutMainRepository
        uses: actions/checkout@v3
      - run: gh pr create -B ${{ matrix.branch }} -t 自動マージ${{ matrix.branch }} -b ""
