name: branch-auto-merge
on: 
  push:
  pull_request:
    types: closed
    branches: main
  workflow_dispatch:

jobs:
  create-branch-list:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.branches.outputs.value }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: create branch list
        id: branchlist
        run: |
          git fetch
          branches=$(git branch -a | grep remotes/origin/develop/ | sed s@remotes/origin/@\"@ | sed s/$/\",/ | sort | sed s/,$//)
          echo "branchlist=[ $branches ]" >> $GITHUB_OUTPUT
  auto-merge-branch-unit:
    needs: create-branch-list
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ github.token }}
    strategy:
      max-parallel: 1
      matrix:
        branch: ${{ fromJson(needs.create-branch-list.outputs.branchlist) }}
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: create pull request
        id: create-pull-request
        #run: gh pr create -B ${{ matrix.branch }} -t "Auto Merge 'main' To "${{ matrix.branch }} -b ""
        #run: git merge --no-ff
        run: |
          git fetch
          temp_list=$(git branch -a | grep remotes/origin/develop/ | sed s@remotes/origin/@\"@ | sed s/$/\",/ | sort )
          list=$(echo $temp_list | sed s/,$// )
          #echo "release_list=[ $list ]" >> $GITHUB_OUTPUT
          echo ${list}
