on: 
  push:  
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      MINOR_MAX: 00
      MINOR_MIN: 00
      REVISION_MAX: 100
      REVISION_MIN: 000
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: update-version
        run: |
          pwd
          # 前提フォーマット：0.00.000
          VERSION=`cat version.txt`
          #1個目の.
          MAJOR=`echo $VERSION | cut -c 1`
          
          #2個目の.
          MINOR=`echo $VERSION | cut -c 3-4`
          REVISION=`echo $VERSION | cut -c 6-8`

          TARGET=`echo $((REVISION + 1))`
          if [${TARGET} -gt ${{ env.REVISION_MAX }}]; then
             MINOR=`echo $((MINOR + 1))`
             REVISION=`echo ${{ env.REVISION_MIN }}`
             
             TARGET=`echo $((MINOR + 1))`
             if [${TARGET} -gt ${{ env.MINOR_MAX }}]; then
               MAJOR=`echo $((MAJOR + 1))`
               MINOR=`echo ${{ env.MINOR_MIN }}`
             fi
          fi
          echo ${MAJOR}
          echo ${MINOR}
          echo ${REVISION}
