on: 
  push:  
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      MINOR_MAX: 99
      REVISION_MAX: 100
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: update-version
        run: |
          pwd
          VERSION=`cat version.txt`
          CURRENT_MAJOR=`echo $VERSION | cut -c 1`
          CURRENT_MINOR=`echo $VERSION | cut -c 3-4`
          CURRENT_REVISION=`echo $VERSION | cut -c 6-8`
          
          NEW_MAJOR=`echo ${CURRENT_MAJOR}`
          NEW_MINOR=`echo ${CURRENT_MINOR}`
          
          RESULT=`expr $CURRENT_REVISION + 1`
          NEW_REVISION=`echo $RESULT`
          if [${NEW_REVISION} -gt ${{ env.REVISION_MAX }}]; then
             NEW_MINOR=`expr $CURRENT_MINOR + 1`
             NEW_REVISION=`echo 0`
             
             if [${NEW_MINOR} -gt ${{ env.MINOR_MAX }}]; then
               NEW_MAJOR=`expr $CURRENT_MAJOR + 1`
               NEW_MINOR=`echo 0`
             fi
          fi
          
          #NEW_VERSION=`printf "%d.%02d.%03d" $NEW_MAJOR $$NEW_MINOR $NEW_REVISION`
          #echo ${NEW_VERSION}
          echo ${NEW_MAJOR}
          echo ${NEW_MINOR}
          echo ${NEW_REVISION}
