on: 
  push:  
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout work branch
        uses: actions/checkout@v3
      - name: create work branch
        run: |
          git push --delete origin sandbox/action-work
          git checkout -b sandbox/action-work main
      - name: update-version
        run: |
          # 定数定義
          MAX_MINOR=99
          MAX_REVISION=999
          
          # バージョン取得
          VERSION=`cat version.txt`
          CURRENT_MAJOR=`echo $VERSION | cut -d "." -f 1`
          CURRENT_MINOR=`echo $VERSION | cut -d "." -f 2`
          CURRENT_REVISION=`echo $VERSION | cut -d "." -f 3`

          # バージョンカウントアップ（基本、リビジョン+1で済む）
          NEW_MAJOR=`echo ${CURRENT_MAJOR}`
          NEW_MINOR=`echo ${CURRENT_MINOR}`          
          NEW_REVISION=`expr $CURRENT_REVISION + 1`
          
          # リビジョンが最大値を超えた場合は、マイナーをカウントアップ
          if [ "$NEW_REVISION" -gt "$MAX_REVISION" ]; then
              NEW_MINOR=`expr $CURRENT_MINOR + 1`
              NEW_REVISION=0
             
              # マイナーが最大値を超えた場合は、メジャーをカウントアップ
              if [ "$NEW_MINOR" -gt "$MAX_MINOR" ]; then
                  NEW_MAJOR=`expr $CURRENT_MAJOR + 1`
                  NEW_MINOR=0
              fi
          fi

          # バージョンupdate
          printf "%d.%02d.%03d" $NEW_MAJOR $NEW_MINOR $NEW_REVISION > version.txt
          cat version.txt
          git push origin sandbox/action-work

          # gh CLIが導入されていること前提
          #gh pr create -B "main" -t "Increment Version" -b ""
          
          # hubコマンドでもprいけるの？https://www.ritolab.com/posts/206
