on: 
  push:  
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      MINOR_MAX: 99
      MINOR_MIN: 00
      REVISION_MAX: 999
      REVISION_MIN: 000
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: update-version
        run: |
          pwd
          # 前提フォーマット：0.00.000
          VERSION=`cat version.txt`
          MAJOR=`echo $VERSION | cut -c 1`#1個目の.
          MINOR=`echo $VERSION | cut -c 3-4`#2個目の.
          REVISION=`echo $VERSION | cut -c 6-8`

          echo ${MAJOR}
          echo ${MINOR}
          echo ${REVISION}
          
          # REVISIONがMAX値の場合は、MINに戻し、MINORをアップ
          # MINORがMAX値の場合は、MINに戻し、MAJORをアップ
          # MAJOR、
          echo $((REVISION + 1)) 
          echo $?
          if [$? -gt ${{ env.REVESION_MAX }}]; then
             MINOR=`echo $((MINOR + 1))`
             REVISION=`echo ${{ env.REVISION_MIN }}`
             
             echo ${MINOR}
             if [$? -gt ${{ env.MINOR_MAX }}]; then
               MAJOR=`echo $((MAJOR + 1))`
               MINOR=`echo ${{ env.MINOR_MIN }}`
             fi
          fi
