on: 
  pull_request:
    types: 
      - opened
    branches: 
      - main
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      WORK_BRANCH: sandbox/action-work
    steps:
      - name: checkout work branch
        uses: actions/checkout@v3
      - name: create work branch
        run: |
          git checkout -b ${{ env.WORK_BRANCH }} main
      - name: update-version
        run: |
          # 定数定義
          MAX_MINOR=99
          MAX_REVISION=999
          
          # バージョン取得
          VERSION=`cat version.txt`
          CURRENT_MAJOR=`echo $VERSION | cut -d "." -f 1`
          CURRENT_MINOR=`echo $VERSION | cut -d "." -f 2`
          CURRENT_REVISION=`echo $VERSION | cut -d "." -f 3`

          # バージョンカウントアップ（基本、リビジョン+1で済む）
          NEW_MAJOR=`echo ${CURRENT_MAJOR}`
          NEW_MINOR=`echo ${CURRENT_MINOR}`          
          NEW_REVISION=`expr $CURRENT_REVISION + 1`
          
          # リビジョンが最大値を超えた場合は、マイナーをカウントアップ
          if [ "$NEW_REVISION" -gt "$MAX_REVISION" ]; then
              NEW_MINOR=`expr $CURRENT_MINOR + 1`
              NEW_REVISION=0
             
              # マイナーが最大値を超えた場合は、メジャーをカウントアップ
              if [ "$NEW_MINOR" -gt "$MAX_MINOR" ]; then
                  NEW_MAJOR=`expr $CURRENT_MAJOR + 1`
                  NEW_MINOR=0
              fi
          fi

          # バージョンupdate
          printf "%d.%02d.%03d" $NEW_MAJOR $NEW_MINOR $NEW_REVISION > version.txt
      - name: push work branch
        run: |
          git add version.txt
          
          # ここの認証なんとかしたい。トークン設定にしよう。
          git config --global user.email "shok2gok.tdos3ky@icloud.com"
          git config --global user.name "0511junpei"
          git commit -m "version更新"

          git push origin ${{ env.WORK_BRANCH }}
      - name: push main branch
        run: |
          gh pr create -B main -t "Increment Version for bot" -b ""
