on: 
  push:  
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main repository
        uses: actions/checkout@v3
      - name: update-version
        run: |
          pwd
          # 前提フォーマット：0.00.000
          VERSION=`cat version.txt`
          MAJOR=`$VERSION | cut -c 1`
          MINOR=`$VERSION | cut -c 3-5`
          REVISION=`$VERSION | cut -c 6-8`
          echo MAJOR
          echo MINOR
          echo REVISION
